name: FormVault

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
      working-directory: backend
    - name: Fmt
      run: cargo fmt
      working-directory: backend

    - name: Run tests
      run: cargo test --verbose
      working-directory: backend

