name: FormVault

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
        working-directory: backend

      - name: Fmt
        run: cargo fmt --all -- --check
        working-directory: backend

      - name: Run tests
        run: cargo test --verbose
        working-directory: backend

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install cargo-release
        run: cargo install --locked cargo-release

      - name: Run cargo release
        working-directory: backend
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo release --execute --no-publish
          # `--no-publish` lets you control publishing separately if you want

      - name: Publish to crates.io
        working-directory: backend
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish
