name: FormVault

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Cd
      run: cd backend
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Fmt
      run: cargo fmt
    - name: Run tests
      run: cargo test --verbose
  
